# NumPy - I
In this session, we will learn about the basics of NumPy, which is the fundamental package for mathematical computing in Python. **NumPy** stands for **Numerical Python**. The primary use of NumPy is efficient data handling and manipulation.

To access `numpy` and its functions import it in your Python code like this: `import numpy as np`

In [1]:
import numpy as np

# NumPy arrays
Arrays are the main ways of storing data when using the `numpy` library. We create these arrays using the `array` method that instantiates an object of the `ndarray` class.

### Example
Creating empty arrays

In [2]:
np_arr = np.array([])
np_arr

array([], dtype=float64)

In [3]:
type(np_arr)

numpy.ndarray

In [4]:
print(np_arr)

[]


In [5]:
len(np_arr)

0

### Example
Creating arrays from lists

In [6]:
some_list = [1, 4, 5, 6]
some_list

[1, 4, 5, 6]

In [7]:
type(some_list)

list

In [8]:
np_arr = np.array(some_list)
np_arr

array([1, 4, 5, 6])

In [9]:
type(np_arr)

numpy.ndarray

In [10]:
print(np_arr)

[1 4 5 6]


In [11]:
len(np_arr)

4

### Example
Creating arrays from tuples

In [12]:
some_tuple = (-5, 1, -4, 7, 2)
print(some_tuple, type(some_tuple))

(-5, 1, -4, 7, 2) <class 'tuple'>


In [14]:
np_arr = np.array(some_tuple)
print(np_arr)

[-5  1 -4  7  2]


In [15]:
type(np_arr)

numpy.ndarray

### Example
Creating arrays from sets

In [16]:
some_set = {1.3, -5.6, 2.8, -6.2, 8.4}
print(some_set, type(some_set))

{1.3, 2.8, 8.4, -6.2, -5.6} <class 'set'>


In [17]:
np_arr = np.array(some_set)
np_arr

array({1.3, 2.8, 8.4, -6.2, -5.6}, dtype=object)

Sets have no inherent ordering. So, it makes little sense to generate arrays from sets.

# Multidimensional arrays
One of NumPy's fundamental features is its ability to handle multidimensional arrays efficiently. A multidimensional array is an array with more than one dimension or axis.

### Example
Creating 2D arrays

In [18]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

### Example
Looking at the number of dimensions or axes in arrays

In [19]:
arr_2d.ndim

2

In [20]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_1d.ndim

1

### Example
Looking at the shape of arrays

In [21]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr_2d.shape # (no. of rows, no. of columns)

(2, 3)

In [22]:
arr_1d.shape

(6,)

In [23]:
arr_2d.size
# Number of elements

6

### Quiz
Extract the size of the array `quiz_arr = np.array([[2, 5, 3, 4], [1, 6, 4, 2], [7, 8, 4,1]])`

In [24]:
quiz_arr = np.array([[2, 5, 3, 4], [1, 6, 4, 2], [7, 8, 4,1]])
quiz_arr.size

12

In [25]:
quiz_arr.shape

(3, 4)

In [26]:
quiz_arr.ndim

2

### Example
Accessing elements from 1D arrays

In [24]:
np_arr = np.array([22, -36, 32, 47, 71, -45])
np_arr

array([ 22, -36,  32,  47,  71, -45])

In [25]:
np_arr[0]

22

In [26]:
np_arr[4]

71

In [27]:
np_arr[-2]

71

### Quiz
Extract the element `'Bob'` from `quiz_arr = np.array(['Adil', 'Bob', 'Chandra', 'Dheeraj', 'Eashwar'])`

In [28]:
quiz_arr = np.array(['Adil', 'Bob', 'Chandra', 'Dheeraj', 'Eashwar'])
quiz_arr[1]

'Bob'

### Example
Accessing elements from 2D arrays

In [29]:
ls=[[1,2,3],[4,5,6]]
ls[1][0]

4

In [30]:
np_arr = np.array([['Python', 'R', 'C++'], [len('Python'), len('R'), len('C++')]])
np_arr

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U21')

In [31]:
np_arr[0][0]

'Python'

In [32]:
np_arr[0,0]

'Python'

In [33]:
np_arr[1][-1]

'3'

In [34]:
np_arr[1,-1]

'3'

### Quiz
Count the number of elements in the following array that are greater than 50:
```
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])
```

In [35]:
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])


In [37]:
len(num_arr[num_arr>50])

14

### Quiz
Count the number of elements in the following array that lie in the range $[50,70]$ (both inclusive):
```
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])
```

In [38]:
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])


In [40]:
len(num_arr[(num_arr>=50) & (num_arr<=70)])
# & --> and
# | --> or

7

In [41]:
len(num_arr[(num_arr>=50) | (num_arr<=70)])

24

In [55]:
# Reshape

In [42]:
np_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [43]:
np_arr.shape

(3, 4)

In [45]:
np_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
reshaped_arr=np_arr.reshape(6,2)
reshaped_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
np_arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

### Quiz
Consider the array shown below:
```
np_arr = np.array([5, 7, -2, 3])
```
Transform `np_arr` to the array shown below:
```
np.array([[5, -2], [7, 3]])
```
Try using the `transpose` method on the previous result

In [48]:
np_arr = np.array([5, 7, -2, 3])
reshaped_array=np_arr.reshape(2,2)
reshaped_array

array([[ 5,  7],
       [-2,  3]])

In [49]:
# Transpose
np_arr.T

array([ 5,  7, -2,  3])

In [50]:
# Transpose
np.transpose(np_arr)

array([ 5,  7, -2,  3])

In [51]:
# Addition

In [59]:
v1 = np.array([[5, -4], [-3, 2]]) 
v2 = np.array([[3, -8], [-6, 1]])

In [53]:
np.add(v1,v2)

array([[  8, -12],
       [ -9,   2]])

In [54]:
v1+v2

array([[  8, -12],
       [ -9,   2]])

In [56]:
np.subtract(v1,v2)

array([[2, 4],
       [3, 2]])

In [57]:
v1-v2

array([[2, 4],
       [3, 2]])

In [60]:
np.divide(v1,v2)

array([[1.66666667, 0.5       ],
       [0.5       , 2.        ]])

In [61]:
np.multiply(v1,v2)

array([[15, 32],
       [18,  2]])

In [62]:
v1*v2

array([[15, 32],
       [18,  2]])

### Quiz
Consider the array shown below:
```
np_arr = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]])
```
What does `np_arr.reshape(-1)` do?

In [63]:
# Special Case of reshape

In [64]:
np_arr = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]])
np_arr.reshape(-1) # n dimension to 1d array

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [66]:
## Flatten

In [65]:
np_arr.flatten()

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [67]:
#np_arr.reshape(-1) is same as np_arr.flatten()