In [1]:
import numpy as np

### Quiz
Consider the arrays shown below:
```
arr_1 = np.array([[1, 3], [-2, 5], [6, 7]])
arr_2 = np.array([[1, -7, 4], [0, 8, -4]])
```
Add the two arrays to produce the following array:
```
np.array([[2, 3], [-9, 13], [10, 3]])
```
You may need to transpose the second array and check whether the elements match accordingly

In [2]:
arr_1 = np.array([[1, 3], [-2, 5], [6, 7]])
arr_2 = np.array([[1, -7, 4], [0, 8, -4]])

In [3]:
arr_1

array([[ 1,  3],
       [-2,  5],
       [ 6,  7]])

In [4]:
arr_2

array([[ 1, -7,  4],
       [ 0,  8, -4]])

In [7]:
out=arr_1+arr_2.transpose()

In [8]:
out

array([[ 2,  3],
       [-9, 13],
       [10,  3]])

### Example
Performing exponentiation with arrays

In [9]:
np_arr = np.array([[1, 0, -1], [2, 0.5, 0.1]])
np_arr

array([[ 1. ,  0. , -1. ],
       [ 2. ,  0.5,  0.1]])

In [10]:
np_arr ** 2

array([[1.  , 0.  , 1.  ],
       [4.  , 0.25, 0.01]])

In [13]:
np_arr ** 3

array([[ 1.00e+00,  0.00e+00, -1.00e+00],
       [ 8.00e+00,  1.25e-01,  1.00e-03]])

In [ ]:
1.25e-01 = 1.25*10^(-1)=0.125

In [14]:
arr=np_arr ** 2

In [15]:
arr

array([[1.  , 0.  , 1.  ],
       [4.  , 0.25, 0.01]])

In [16]:
np.sqrt(arr)

array([[1. , 0. , 1. ],
       [2. , 0.5, 0.1]])

In [17]:
company_revenue_jan = np.array([2450.67, 1872.34, 1098.44])
company_revenue_jan

array([2450.67, 1872.34, 1098.44])

In [18]:
company_revenue_jan.sum()

5421.450000000001

### Quiz
Define a function called `return_exp_array` that takes in an array and returns an array whose elements are exponentiated versions of the original elements. Consider the exponent as an input to the function as well.

Here is a test case to help you out:
> The output of `return_exp_array(np.array([0, 2], [-2, -1]), 4)` should be `np.array([0, 16], [16, 1])`

In [19]:
def return_exp_array(in_arr, exp_val): 
    return in_arr ** exp_val
return_exp_array(np.array([[0, 2], [-2, -1]]), 4)

array([[ 0, 16],
       [16,  1]])

In [20]:
monthly_rates = np.array([[2, 25, 45], [10, 16, 8], [4, 3, 12]])
monthly_rates

array([[ 2, 25, 45],
       [10, 16,  8],
       [ 4,  3, 12]])

In [21]:
monthly_rates.sum()

125

In [22]:
monthly_rates.sum(axis = 0)# columnwise sum

array([16, 44, 65])

In [23]:
monthly_rates.sum(axis = 1)

array([72, 34, 19])

In [25]:
monthly_rates

array([[ 2, 25, 45],
       [10, 16,  8],
       [ 4,  3, 12]])

In [26]:
monthly_rates.prod()

414720000

In [27]:
monthly_rates.prod(axis = 0)

array([  80, 1200, 4320])

In [28]:
monthly_rates.prod(axis = 1)

array([2250, 1280,  144])

In [29]:
monthly_rates.mean()

13.88888888888889

In [30]:
monthly_rates.mean(axis = 0)

array([ 5.33333333, 14.66666667, 21.66666667])

In [31]:
monthly_rates.mean(axis = 1)

array([24.        , 11.33333333,  6.33333333])

### Example
Rounding

In [32]:
np_arr = np.array([1.56, 2.765, -3.33, 5.102, 6.6464])
np_arr

array([ 1.56  ,  2.765 , -3.33  ,  5.102 ,  6.6464])

In [33]:
np.round(a = np_arr, decimals = 2)

array([ 1.56,  2.76, -3.33,  5.1 ,  6.65])

In [34]:
np_arr

array([ 1.56  ,  2.765 , -3.33  ,  5.102 ,  6.6464])

In [35]:
np_arr = np.round(a = np_arr, decimals = 3)
np_arr

array([ 1.56 ,  2.765, -3.33 ,  5.102,  6.646])

In [36]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### Quiz
Create the following array:
```
np.array[-7, -6.5, -6, -5.5, -5, -4.5, -4, -3.5, -3, -2.5, -2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4.]
```

In [41]:
np.arange(-7,4.5,0.5)

array([-7. , -6.5, -6. , -5.5, -5. , -4.5, -4. , -3.5, -3. , -2.5, -2. ,
       -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,
        4. ])

### Quiz
Create an array with 20 entries starting with the number $-10$ and ending with the number $10$

In [42]:
np.linspace(-10, 10, 20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

### Example
Generating some standard arrays

In [54]:
np.zeros(shape = (2, 2))

array([[0., 0.],
       [0., 0.]])

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.ones(shape = (3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.eye(5)
# Idendity Matrix is a Sqaure matrix (no. of rows = no. of columns)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.full((3,4),fill_value=5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Example
Random number generation

In [57]:
np.random.randint(low = 1, high = 5, size = (2,3))

array([[2, 3, 3],
       [1, 1, 1]])

In [ ]:
#max,min,median